server:
  port: 8080
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    username:
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ysoztf.security.entity